export { ReactComponent as IconCopy } from './copy.svg?react'
export { ReactComponent as IconHistory } from './history.svg?react'
export { ReactComponent as IconLeftArrow } from './left-arrow.svg?react'
export { ReactComponent as IconLogout } from './logout.svg?react'
export { ReactComponent as IconSettngs } from './settings.svg?react'
export { ReactComponent as IconSwap } from './swap.svg?react'
