export enum Statuses {
  STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED',
  STATUS_CREATED = 'STATUS_CREATED',
  STATUS_PENDING = 'STATUS_PENDING',
  STATUS_SUCCESS = 'STATUS_SUCCESS',
  STATUS_FAILED = 'STATUS_FAILED',
  STATUS_UNKNOWN = 'STATUS_UNKNOWN'
}
